export type CharacterEngineErrorCode =
  | 'ABILITY_SCORE_OUT_OF_RANGE'
  | 'POINT_BUY_OVER_BUDGET'
  | 'STANDARD_ARRAY_DUPLICATE'
  | 'STANDARD_ARRAY_INVALID'
  | 'DIE_ROLL_OUT_OF_RANGE'
  | 'HP_INPUT_INVALID'
  | 'DYING_INPUT_INVALID'
  | 'ARCHETYPE_INPUT_INVALID'
  | 'LOADOUT_INPUT_INVALID'
  | 'RECORD_INPUT_INVALID'
  | 'ROSTER_INPUT_INVALID'
  | 'SELECTION_NOT_FOUND'
  | 'TIME_INPUT_INVALID'
  | 'XP_INPUT_INVALID'
  | 'FEATURE_TEMPLATE_INVALID'
  | 'EMERGENT_INPUT_INVALID'
  | 'LEVEL_UP_INVALID'
  | 'DEATH_MODE_INVALID'
  | 'DEATH_MODE_NOT_SET'
  | 'DEATH_INPUT_INVALID'
  | 'AUTOSAVE_INPUT_INVALID'
  | 'AUTOSAVE_NOT_FOUND'
  | 'OBITUARY_REQUIRED'
  | 'RESPAWN_LIMIT_EXCEEDED'
  | 'RESPAWN_COST_INSUFFICIENT'
  | 'COMPANION_INPUT_INVALID'
  | 'COMPANION_STEP_INVALID'
  | 'COMPANION_NOT_FOUND'
  | 'PROXY_INPUT_INVALID'
  | 'PROXY_ACTION_UNAVAILABLE'
  | 'LOCATION_INPUT_INVALID'

export class CharacterEngineError extends Error {
  readonly code: CharacterEngineErrorCode

  constructor(code: CharacterEngineErrorCode, message: string) {
    super(message)
    this.name = 'CharacterEngineError'
    this.code = code
  }
}
