/**
 * Compute a safe implementation order for /board epics from their
 * **Depends on:** lines. Epic ids are grouped by package/theme, not by
 * dependency order, so numeric order alone is not a safe execution order —
 * this generates board/IMPLEMENTATION-ORDER.md so agents (and humans) have
 * an explicit wave-by-wave sequence instead of discovering missing
 * dependencies ticket by ticket.
 */
import fs from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const BOARD = join(ROOT, 'board')
const OUT_PATH = join(BOARD, 'IMPLEMENTATION-ORDER.md')

/** @param {string} content */
export function parseDependsOn(content) {
  // Stop at Feeds or a blank line. Use \r?\n so Windows CRLF board files
  // do not swallow the rest of the epic (which falsely pulls AC ticket refs).
  const match = content.match(/\*\*Depends on:\*\*([\s\S]*?)(?:\*\*Feeds:\*\*|\r?\n\r?\n|$)/)
  if (!match) return []
  const span = match[1].trim()
  // Authors write "none (… parallel to `012-…`)" for foundation epics; those
  // backtick refs are illustrations, not dependencies.
  if (/^none\b/i.test(span)) return []
  return [...new Set(span.match(/\d{3}/g) || [])]
}

/**
 * @typedef {{ id: string, base: string, state: 'backlog'|'in-progress'|'done', dependsOn: string[] }} Epic
 * @param {Epic[]} epics
 */
export function findNumericOrderViolations(epics) {
  const byId = new Map(epics.map((e) => [e.id, e]))
  const doneIds = new Set(epics.filter((e) => e.state === 'done').map((e) => e.id))
  const violations = []
  for (const epic of epics) {
    if (epic.state === 'done') continue
    for (const dep of epic.dependsOn) {
      if (!byId.has(dep) || doneIds.has(dep)) continue
      if (Number(dep) > Number(epic.id)) {
        violations.push({ id: epic.id, dependsOn: dep })
      }
    }
  }
  return violations
}

/** @param {Epic[]} epics */
export function computeWaves(epics) {
  const byId = new Map(epics.map((e) => [e.id, e]))
  const doneIds = new Set(epics.filter((e) => e.state === 'done').map((e) => e.id))
  const remaining = new Set(epics.filter((e) => e.state !== 'done').map((e) => e.id))

  const unmetDeps = (id) => byId.get(id).dependsOn.filter((d) => byId.has(d) && !doneIds.has(d))

  const waves = []
  while (remaining.size > 0) {
    const wave = [...remaining].filter((id) => unmetDeps(id).every((d) => !remaining.has(d))).sort()
    if (wave.length === 0) {
      throw new Error(`Circular dependency among: ${[...remaining].sort().join(', ')}`)
    }
    waves.push(wave)
    for (const id of wave) remaining.delete(id)
  }
  return waves
}

/** @param {string} boardRoot */
function discoverEpics(boardRoot) {
  const epics = []
  for (const state of ['backlog', 'in-progress', 'done']) {
    const dir = join(boardRoot, state)
    if (!fs.existsSync(dir)) continue
    for (const name of fs.readdirSync(dir)) {
      if (!name.endsWith('.md')) continue
      const base = name.slice(0, -3)
      const m = base.match(/^(\d{3})(?:\.(\d+))?-/)
      if (!m || m[2]) continue
      const content = fs.readFileSync(join(dir, name), 'utf-8')
      epics.push({ id: m[1], base, state, dependsOn: parseDependsOn(content) })
    }
  }
  return epics
}

/** @param {Epic[]} epics @param {string[][]} waves */
function formatDoc(epics, waves) {
  const byId = new Map(epics.map((e) => [e.id, e]))
  const pendingCount = epics.filter((e) => e.state !== 'done').length
  const lines = [
    '# Implementation order',
    '',
    '**Generated by `npm run board:order` — do not hand-edit, regenerate instead** ' +
      '(after adding new epics, or any time `**Depends on:**` lines change).',
    '',
    'Epic ids are grouped by package/theme (e.g. `021`-`031` = CharacterEngine), **not** by ' +
      'dependency order. Picking tickets in numeric order alone will hand you one before ' +
      'something it depends on exists. Work wave by wave instead: everything in a wave has no ' +
      'unmet dependency on anything else still pending, so tickets within a wave can run in ' +
      'any order (including in parallel).',
    '',
    `${waves.length} waves, ${pendingCount} pending epics.`,
    ''
  ]
  waves.forEach((wave, i) => {
    lines.push(`## Wave ${i + 1}`, '')
    for (const id of wave) {
      const epic = byId.get(id)
      const tag = epic.state === 'in-progress' ? ' _(in-progress)_' : ''
      lines.push(`- \`${epic.base}\`${tag}`)
    }
    lines.push('')
  })
  return lines.join('\n')
}

export function main(argv = process.argv.slice(2)) {
  const epics = discoverEpics(BOARD)
  const violations = findNumericOrderViolations(epics)
  const waves = computeWaves(epics)

  if (argv.includes('--check')) {
    console.log(
      `${waves.length} waves, ${epics.filter((e) => e.state !== 'done').length} pending epics, ` +
        `${violations.length} numeric-order violation(s) (expected — see board/IMPLEMENTATION-ORDER.md).`
    )
    return 0
  }

  fs.writeFileSync(OUT_PATH, formatDoc(epics, waves))
  console.log(`Wrote ${OUT_PATH} (${waves.length} waves, ${violations.length} numeric-order violations noted).`)
  return 0
}

const isDirectRun =
  process.argv[1] &&
  (process.argv[1].endsWith('board-order.mjs') ||
    process.argv[1].replace(/\\/g, '/').endsWith('scripts/board-order.mjs'))

if (isDirectRun) {
  process.exitCode = main()
}
